apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-app
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - name: streaming-processor
        image: gcr.io/krotonapp/nginx-rtmp